name: Experiment Modification Issue
description: (w/ Approved Discussion) Create an issue to track an addition to an existing experiment
title: "⚙️ [Enhancment]"
labels: ["enhancment"]
body:
- type: markdown
  attributes: 
    value: |
      ## Before you begin
      🚨 **Please do not skip instructions**🚨
      
      This template is to be used with an approved proposal on the [experiment's discussion entry](https://github.com/CommunityToolkit/Labs-Windows/discussions/categories/experiments).

      This info is essential to help us process your experiment.

- type: textarea
  id: problem-statement
  validations: 
    required: true
  attributes: 
    label: Problem Statement
    description: Copy your problem statement description from your approved discussion.
    placeholder: |
      A clear and concise description of what the problem the experiment solves, starting with the user story.

- type: textarea
  id: overview-description
  validations: 
    required: true
  attributes: 
    label: Overview
    description: What feature or enhancment will be added to this component?
    value: |
      This enhancment adds the following components:
       - **Feature/Enhancment One** a ...
       - **Feature/Enhancment Two** a ...

- type: textarea
  id: additional-info
  attributes:
    label: Additional info
    description: Add any other context or screenshots about the feature request here.

- type: checkboxes
  id: implementation-requirements
  attributes:
    label: Implementation Requirements
    description: Not all these items are required to submit a PR. This list is here to help track what is remaining to implement before a technical review and discussion of moving into the main repository can occur.
    options:
      - label: Working Prototype
      - label: Feature Complete
      - label: Documentation
      - label: Samples
      - label: Unit Tests
      - label: Community Feedback / Usage Testimonies

- type: checkboxes
  id: tested-platforms
  attributes:
    label: Tested Platforms
    description: Which platforms has your current experiment code been tested with (by you or someone in the community)?
    options:
      - label: UWP
      - label: WinAppSDK / WinUI 3
      - label: Web Assembly (WASM)
      - label: Android
      - label: iOS
      - label: MacOS
      - label: Linux / GTK

- type: checkboxes
  id: technical-review
  attributes:
    label: Technical Review
    description: These items can sometimes be done ahead of time, but are usually started and completed after all implementation details are finished. You can _skip_ this section for now when opening a new experiment, though it's good to be familiar with these work items.
    options:
      - label: Accessibility Audit
      - label: API/Naming Review
      - label: Code Quality/Style
      - label: Dependency Review
      - label: Design/Style Review
      - label: Final Approval

- type: dropdown
  id: contribution
  attributes:
    label: Community Help?
    description: Would you like others to help you work on the deliverables for this experiment?
    options:
      - "Yes"
      - "No"
